### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by jaredatandi** [raihan2bd/portfolio-mobile-first#5]
## Improvement areas:
- It would be better to be more descriptive in your commit messages
- Add padding in between the cards in the recent works section

**Comment by sleekhub** [comment]
# Changes to be made ♻️ 
Great job with the code 
code was well documented and structured👍 
however you can make some changes to your desktop version button
it has to be centered just like the figma design
you can also adjust the on hover on the button color to improve the contrast
![ABU](https://user-images.githubusercontent.com/113626558/201026450-0bdf3915-0cb4-432d-aa24-a4177babed36.JPG)
